'use client';

import { useEffect, useState, useCallback } from 'react';
import { createClient } from '@/utils/supabase/client';
import type { Database } from '@/types/database';
import { toast } from 'sonner';
import { parseCSV } from '@/lib/csv-parser';

type Profilo = Database['public']['Tables']['profilo']['Row'];
type ProfiloUpdate = Database['public']['Tables']['profilo']['Update'];
type Operazione = Database['public']['Tables']['operazione']['Insert'];

export interface UseImpostazioniReturn {
  profilo: Profilo | null;
  isLoading: boolean;
  isSaving: boolean;
  aggiornaProfilo: (data: ProfiloUpdate) => Promise<void>;
  importaCSV: (csvContent: string, brokerType: string) => Promise<number>;
  esportaCSV: () => Promise<string>;
  eliminaTuttiDati: () => Promise<void>;
  logout: () => Promise<void>;
}

export function useImpostazioni(): UseImpostazioniReturn {
  const [profilo, setProfilo] = useState<Profilo | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  const fetchProfilo = useCallback(async () => {
    try {
      setIsLoading(true);
      const supabase = createClient();

      const {
        data: { session },
        error: sessionError,
      } = await supabase.auth.getSession();

      if (sessionError || !session) {
        toast.error('Sessione non trovata');
        setIsLoading(false);
        return;
      }

      const userId = session.user.id;

      const { data, error } = await (supabase as any)
        .from('profilo')
        .select('*')
        .eq('id', userId)
        .single();

      if (error) {
        console.error('Errore nel caricamento profilo:', error);
        toast.error('Errore nel caricamento del profilo');
      } else if (data) {
        setProfilo(data);
      }
    } catch (error) {
      console.error('Errore nel caricamento profilo:', error);
      toast.error('Errore sconosciuto');
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchProfilo();
  }, [fetchProfilo]);

  const aggiornaProfilo = useCallback(
    async (data: ProfiloUpdate) => {
      try {
        setIsSaving(true);
        const supabase = createClient();

        const {
          data: { session },
          error: sessionError,
        } = await supabase.auth.getSession();

        if (sessionError || !session) {
          toast.error('Sessione non trovata');
          return;
        }

        const userId = session.user.id;

        const { error } = await (supabase as any)
          .from('profilo')
          .update(data)
          .eq('id', userId);

        if (error) {
          console.error('Errore nell\'aggiornamento profilo:', error);
          toast.error('Errore nell\'aggiornamento del profilo');
        } else {
          toast.success('Profilo aggiornato con successo');
          await fetchProfilo();
        }
      } catch (error) {
        console.error('Errore nell\'aggiornamento profilo:', error);
        toast.error('Errore sconosciuto');
      } finally {
        setIsSaving(false);
      }
    },
    [fetchProfilo]
  );

  const importaCSV = useCallback(
    async (csvContent: string, brokerType: string): Promise<number> => {
      try {
        setIsSaving(true);
        const supabase = createClient();

        const {
          data: { session },
          error: sessionError,
        } = await supabase.auth.getSession();

        if (sessionError || !session) {
          toast.error('Sessione non trovata');
          return 0;
        }

        const userId = session.user.id;

        // Parse CSV
        let operazioni: Operazione[] = [];
        try {
          operazioni = parseCSV(csvContent, brokerType) as any;
        } catch (parseError) {
          toast.error('Errore nel parsing del CSV: ' + (parseError as Error).message);
          return 0;
        }

        if (operazioni.length === 0) {
          toast.error('Nessuna operazione trovata nel file');
          return 0;
        }

        // Add profilo_id to all operations
        // Note: ID will be auto-generated by Supabase
        const operazioniConProfilo = operazioni.map((op) => ({
          ...op,
          profilo_id: userId,
          data_apertura: op.data_apertura,
          tipo_ordine: op.tipo_ordine || 'MARKET',
          stato: op.prezzo_uscita ? 'CHIUSA' : 'APERTA',
        }));

        // Insert operations
        const { error } = await (supabase as any)
          .from('operazione')
          .insert(operazioniConProfilo);

        if (error) {
          console.error('Errore nell\'importazione:', error);
          toast.error('Errore nell\'importazione delle operazioni');
          return 0;
        }

        toast.success(`${operazioni.length} operazioni importate con successo`);
        return operazioni.length;
      } catch (error) {
        console.error('Errore nell\'importazione:', error);
        toast.error('Errore sconosciuto');
        return 0;
      } finally {
        setIsSaving(false);
      }
    },
    []
  );

  const esportaCSV = useCallback(async (): Promise<string> => {
    try {
      setIsSaving(true);
      const supabase = createClient();

      const {
        data: { session },
        error: sessionError,
      } = await supabase.auth.getSession();

      if (sessionError || !session) {
        toast.error('Sessione non trovata');
        return '';
      }

      const userId = session.user.id;

      const { data, error } = await (supabase as any)
        .from('operazione')
        .select('*')
        .eq('profilo_id', userId)
        .order('data_apertura', { ascending: true });

      if (error) {
        console.error('Errore nell\'esportazione:', error);
        toast.error('Errore nell\'esportazione dei dati');
        return '';
      }

      if (!data || data.length === 0) {
        toast.error('Nessuna operazione da esportare');
        return '';
      }

      // Convert to CSV
      const headers = [
        'Data Apertura',
        'Simbolo',
        'Direzione',
        'Tipo Ordine',
        'Prezzo Entrata',
        'Quantità',
        'Prezzo Uscita',
        'Quantità Uscita',
        'P&L',
        'P&L %',
        'Commissione',
        'Stato',
        'Note',
      ];

      const rows = data.map((op: any) => [
        op.data_apertura,
        op.simbolo,
        op.direzione,
        op.tipo_ordine,
        op.prezzo_entrata.toString(),
        op.quantita.toString(),
        op.prezzo_uscita?.toString() || '',
        op.quantita_uscita?.toString() || '',
        op.pnl?.toString() || '',
        op.pnl_percentuale?.toString() || '',
        op.commissione.toString(),
        op.stato,
        op.note || '',
      ]);

      // Escape CSV fields
      const escapedRows = rows.map((row: any) =>
        row.map((field: any) => {
          if (typeof field === 'string' && (field.includes(',') || field.includes('"') || field.includes('\n'))) {
            return `"${field.replace(/"/g, '""')}"`;
          }
          return field;
        })
      );

      const csv = [headers, ...escapedRows].map((row) => row.join(',')).join('\n');

      // Download
      const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement('a');
      const url = URL.createObjectURL(blob);
      link.setAttribute('href', url);
      link.setAttribute('download', `gg-tracker-export-${new Date().toISOString().split('T')[0]}.csv`);
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      toast.success('Dati esportati con successo');
      return csv;
    } catch (error) {
      console.error('Errore nell\'esportazione:', error);
      toast.error('Errore sconosciuto');
      return '';
    } finally {
      setIsSaving(false);
    }
  }, []);

  const eliminaTuttiDati = useCallback(async () => {
    try {
      setIsSaving(true);
      const supabase = createClient();

      const {
        data: { session },
        error: sessionError,
      } = await supabase.auth.getSession();

      if (sessionError || !session) {
        toast.error('Sessione non trovata');
        return;
      }

      const userId = session.user.id;

      // Elimina operazioni
      const { error: deleteOpError } = await (supabase as any)
        .from('operazione')
        .delete()
        .eq('profilo_id', userId);

      if (deleteOpError) throw deleteOpError;

      // Elimina strategie
      const { error: deleteStratError } = await (supabase as any)
        .from('strategia')
        .delete()
        .eq('profilo_id', userId);

      if (deleteStratError) throw deleteStratError;

      // Elimina tag e categorie tag (non-system)
      const { error: deleteTagError } = await (supabase as any)
        .from('categoria_tag')
        .delete()
        .eq('profilo_id', userId);

      if (deleteTagError) throw deleteTagError;

      // Elimina obiettivi
      const { error: deleteObjError } = await (supabase as any)
        .from('obiettivo')
        .delete()
        .eq('profilo_id', userId);

      if (deleteObjError) throw deleteObjError;

      // Elimina routine
      const { error: deleteRoutineError } = await (supabase as any)
        .from('routine')
        .delete()
        .eq('profilo_id', userId);

      if (deleteRoutineError) throw deleteRoutineError;

      toast.success('Tutti i dati sono stati eliminati con successo');
    } catch (error) {
      console.error('Errore nell\'eliminazione dei dati:', error);
      toast.error('Errore nell\'eliminazione dei dati');
    } finally {
      setIsSaving(false);
    }
  }, []);

  const logout = useCallback(async () => {
    try {
      const supabase = createClient();

      const { error } = await supabase.auth.signOut();

      if (error) {
        toast.error('Errore nel logout');
        console.error(error);
      } else {
        toast.success('Logout effettuato con successo');
        // Redirect to login
        window.location.href = '/login';
      }
    } catch (error) {
      console.error('Errore nel logout:', error);
      toast.error('Errore sconosciuto');
    }
  }, []);

  return {
    profilo,
    isLoading,
    isSaving,
    aggiornaProfilo,
    importaCSV,
    esportaCSV,
    eliminaTuttiDati,
    logout,
  };
}
